---
# Source: iter8-controller/templates/default/manager.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: iter8
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: iter8
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: iter8
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      containers:
      - command:
        - /manager
        image: "fabolive/iter8-controller:0.1.0"
        imagePullPolicy: Always
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10

---
# Source: iter8-controller/templates/default/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: iter8

---
# Source: iter8-controller/templates/crds/iter8_v1alpha1_experiment.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: experiments.iter8.tools
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type == 'ExperimentCompleted')].status
    description: Whether experiment is completed
    format: byte
    name: completed
    type: string
  - JSONPath: .status.conditions[?(@.type == 'Ready')].reason
    description: Status of the experiment
    format: byte
    name: status
    type: string
  - JSONPath: .spec.targetService.baseline
    description: Name of baseline
    format: byte
    name: baseline
    type: string
  - JSONPath: .status.trafficSplitPercentage.baseline
    description: Traffic percentage for baseline
    format: int32
    name: percentage
    type: integer
  - JSONPath: .spec.targetService.candidate
    description: Name of candidate
    format: byte
    name: candidate
    type: string
  - JSONPath: .status.trafficSplitPercentage.candidate
    description: Traffic percentage for candidate
    format: int32
    name: percentage
    type: integer
  group: iter8.tools
  names:
    categories:
    - all
    - iter8
    kind: Experiment
    plural: experiments
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            analysis:
              properties:
                analyticsService:
                  type: string
                grafanaEndpoint:
                  type: string
                successCriteria:
                  items:
                    properties:
                      metricName:
                        enum:
                        - iter8_latency
                        - iter8_error_rate
                        - iter8_error_count
                        type: string
                      sampleSize:
                        format: int64
                        type: integer
                      stopOnFailure:
                        type: boolean
                      tolerance:
                        format: double
                        type: number
                      toleranceType:
                        enum:
                        - threshold
                        - delta
                        type: string
                    required:
                    - metricName
                    - toleranceType
                    - tolerance
                    type: object
                  type: array
              type: object
            targetService:
              properties:
                baseline:
                  type: string
                candidate:
                  type: string
              type: object
            trafficControl:
              properties:
                interval:
                  type: string
                maxIterations:
                  format: int64
                  type: integer
                maxTrafficPercentage:
                  format: double
                  type: number
                onSuccess:
                  enum:
                  - baseline
                  - candidate
                  - both
                  type: string
                strategy:
                  enum:
                  - check_and_increment
                  - increment_without_check
                  type: string
                trafficStepSize:
                  format: double
                  type: number
              type: object
          required:
          - targetService
          type: object
        status:
          properties:
            analysisState:
              type: object
            assessment:
              properties:
                conclusions:
                  items:
                    type: string
                  type: array
              type: object
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            currentIteration:
              format: int64
              type: integer
            endTimestamp:
              type: string
            grafanaURL:
              type: string
            lastIncrementTime:
              format: date-time
              type: string
            observedGeneration:
              format: int64
              type: integer
            startTimestamp:
              type: string
            trafficSplitPercentage:
              properties:
                baseline:
                  format: int64
                  type: integer
                candidate:
                  format: int64
                  type: integer
              required:
              - baseline
              - candidate
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
# Source: iter8-controller/templates/rbac/rbac_role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - iter8.tools
  resources:
  - experiments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - iter8.tools
  resources:
  - experiments/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - serving.knative.dev
  resources:
  - services/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

---
# Source: iter8-controller/templates/rbac/rbac_role_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: iter8

